import Link from 'next/link';
import Header from '../components/Header';
import Footer from '../components/Footer';
import { homeAssets0 } from '../data/homeAssets0';
import { homeAssets1 } from '../data/homeAssets1';
import { homeAssets2 } from '../data/homeAssets2';

const categories = [
  ['Smartfony Premium', 'kategorie i podkategorie', '01'], ['Laptopy Premium', 'kategorie i podkategorie', '02'],
  ['Energia i Fotowoltaika', 'kategorie i podkategorie', '03'], ['HVAC', 'kategorie i podkategorie', '04'],
  ['Meble Premium', 'kategorie i podkategorie', '05'], ['Drzwi i Bramy Premium', 'kategorie i podkategorie', '06'],
  ['Maszyny i Sprzęt Ciężki', 'kategorie i podkategorie', '07'], ['Wyposażenie Przedsiębiorstw', 'kategorie i podkategorie', '08'],
  ['Wellness Premium', 'kategorie i podkategorie', '09'], ['Smart Home Premium', 'kategorie i podkategorie', '10'],
  ['Luxury Interior', 'kategorie i podkategorie', '11'], ['Outdoor Luxury', 'kategorie i podkategorie', '12'],
  ['Premium Lighting', 'kategorie i podkategorie', '13'], ['Executive Office', 'kategorie i podkategorie', '14'],
  ['Hospitality Premium', 'kategorie i podkategorie', '15'], ['Audio Video Premium', 'kategorie i podkategorie', '16'],
  ['E-Mobility', 'kategorie i podkategorie', '17'], ['Leisure Premium', 'kategorie i podkategorie', '18'],
];

const originalSmartphones = [
  { image: homeAssets1.nubia01, brand:'nubia', model:'Z80 Ultra', retailEur:799, profesjaPln:2765, availability:'oficjalna dystrybucja UE — dostępność potwierdzana przed zamówieniem', use:'fotografia mobilna, multimedia, praca mobilna, komunikacja 5G i wymagające aplikacje', purpose:'flagowy smartfon premium do zastosowań biznesowych i multimedialnych', functions:'ekran OLED klasy premium, wysoka wydajność, zaawansowane foto/wideo, 5G i NFC', warranty:'warunki gwarancji producenta i RMA potwierdzane dla wybranego wariantu przed zamówieniem', manualUrl:'https://eu.nubia.com/pages/nubia-z80-ultra', videoUrl:'https://www.nubia.com/en/products/smartphones/nubia/nubia-z80-ultra.html' },
  { image: homeAssets1.nubia02, brand:'nubia', model:'Z70S Ultra', retailEur:669, profesjaPln:2315, availability:'oficjalna dystrybucja UE — wariant i stan magazynowy potwierdzane przed zamówieniem', use:'fotografia, multimedia, praca mobilna i komunikacja biznesowa', purpose:'smartfon klasy premium dla użytkowników wymagających wysokiej jakości foto/wideo i wydajności', functions:'wyświetlacz AMOLED, 5G, NFC, szybkie ładowanie i rozbudowany zestaw aparatów', warranty:'warunki gwarancji producenta i RMA potwierdzane przed finalną ofertą', manualUrl:'https://eu.nubia.com/', videoUrl:'https://www.nubia.com/en/products/smartphones/' },
  { image: homeAssets1.nubia03, brand:'nubia', model:'Z70 Ultra', retailEur:529, profesjaPln:1831, availability:'oficjalny model marki nubia — dostępność zależna od wariantu', use:'fotografia, praca mobilna, multimedia i komunikacja 5G', purpose:'flagowy telefon do zastosowań biznesowych i multimedialnych', functions:'AMOLED klasy premium, 5G, NFC, zaawansowany aparat i szybkie ładowanie', warranty:'warunki gwarancji producenta i RMA potwierdzane dla konkretnego wariantu', manualUrl:'https://eu.nubia.com/en-de/pages/nubia-z70-ultra', videoUrl:'https://eu.nubia.com/en-de/pages/nubia-z70-ultra' },
  { image: homeAssets1.nubia04, brand:'REDMAGIC', model:'11 Pro', retailEur:699, profesjaPln:2419, availability:'oryginalny smartfon gamingowy REDMAGIC — dostępność potwierdzana przed zamówieniem', use:'gaming mobilny, streaming, multimedia i zadania wysokiej wydajności', purpose:'flagowy smartfon gamingowy do długotrwałych obciążeń', functions:'flagowa platforma mobilna, aktywne chłodzenie, szybki ekran i funkcje gamingowe', warranty:'warunki gwarancji producenta i RMA potwierdzane przed zamówieniem', manualUrl:'https://eu.redmagic.gg/products/redmagic-11-pro/', videoUrl:'https://eu.redmagic.gg/products/redmagic-11-pro/' },
  { image: homeAssets2.nubia05, brand:'REDMAGIC', model:'11 Air', retailEur:599, profesjaPln:2073, availability:'oryginalny smartfon gamingowy REDMAGIC — wariant pamięci potwierdzany przed zamówieniem', use:'gaming mobilny, multimedia, komunikacja i mobilna praca', purpose:'smukły smartfon gamingowy o wysokiej wydajności', functions:'szybki ekran, wydajna platforma mobilna, funkcje gamingowe i łączność 5G', warranty:'warunki gwarancji producenta i RMA potwierdzane dla wybranego wariantu', manualUrl:'https://eu.redmagic.gg/', videoUrl:'https://eu.redmagic.gg/' },
  { image: homeAssets2.nubia06, brand:'REDMAGIC', model:'10S Pro', retailEur:609, profesjaPln:2107, availability:'oryginalny model REDMAGIC — dostępność może być ograniczona', use:'gry mobilne, streaming, multimedia i wymagające aplikacje', purpose:'wysokowydajny smartfon gamingowy do intensywnej pracy i rozrywki', functions:'aktywny system chłodzenia, szybki ekran, 5G i funkcje gamingowe', warranty:'warunki gwarancji producenta i RMA potwierdzane przed finalną ofertą', manualUrl:'https://eu.redmagic.gg/', videoUrl:'https://eu.redmagic.gg/' },
  { image: homeAssets2.nubia07, brand:'REDMAGIC', model:'10 Air', retailEur:449, profesjaPln:1554, availability:'oryginalny model REDMAGIC — dostępność może być ograniczona', use:'gaming mobilny, multimedia i codzienna komunikacja 5G', purpose:'mobilny smartfon gamingowy o smukłej konstrukcji', functions:'szybki ekran, chłodzenie, 5G i rozbudowane funkcje multimedialne', warranty:'warunki gwarancji producenta i RMA potwierdzane dla konkretnego wariantu', manualUrl:'https://eu.redmagic.gg/products/redmagic-10-air', videoUrl:'https://eu.redmagic.gg/products/redmagic-10-air' },
];

export default function Home() {
  return <><Header/><main className="premium-home">
    <section aria-label="Dni otwarcia i obsługa B2B" style={{display:'flex',alignItems:'center',justifyContent:'space-between',gap:20,padding:'14px 24px',borderBottom:'1px solid #2f373b',background:'linear-gradient(90deg, rgba(192,155,70,.14), rgba(8,15,19,.96))'}}><div><strong style={{color:'#f0d778',letterSpacing:'.16em'}}>DNI OTWARCIA</strong><span style={{marginLeft:14,color:'#d8d8d8'}}>Obsługa zapytań B2B i wycen indywidualnych online</span></div><Link href="/contact" style={{color:'#f0d778',fontWeight:700,textDecoration:'none'}}>KONTAKT →</Link></section>

    <section className="commerce-hero">
      <div className="commerce-hero__brand"><img src="/profesja-logo.svg" alt="Logo PROFESJA PREMIUM LIMITED" style={{width:112,height:112,objectFit:'contain',marginBottom:12}}/><p className="eyebrow">Agencja Finansowo-Handlowa B2B</p><h1>PROFESJA</h1><div className="brand-gold">PREMIUM LIMITED™</div><h2>KOMPLEKSOWE ROZWIĄZANIA DLA BIZNESU</h2><p className="hero-services">FINANSOWANIE • IMPORT • SOURCING • LOGISTYKA</p><p style={{maxWidth:560,lineHeight:1.7,color:'#c9c9c9'}}>Profesjonalna obsługa przedsiębiorstw: dobór oryginalnych produktów markowych, organizacja dostaw, zapytania ofertowe oraz indywidualne wsparcie handlowe.</p><div className="cta-row" style={{marginTop:24}}><Link href="/offers/new"><button>ZAPYTAJ O OFERTĘ</button></Link><Link href="/catalog"><button className="cta-secondary">ZOBACZ KATALOG</button></Link></div></div>
      <div className="product-stage" aria-label="Oryginalne smartfony nubia i REDMAGIC"><div className="stage-glow"/><div className="featured-stage-photo"><img src={originalSmartphones[0].image} alt="Materiał produktowy marki nubia / REDMAGIC"/></div><div className="stage-plinth"/></div>
      <aside className="commerce-hero__offer"><div className="brand-offer-label">ORYGINALNE SMARTFONY PREMIUM</div><img src={homeAssets0.nubiaBrand} alt="nubia / REDMAGIC" style={{width:'100%',maxWidth:250,margin:'14px 0',borderRadius:10}}/><div className="feature-row"><span><b>01</b>Zdjęcia</span><span><b>02</b>Wideo / demo</span><span><b>03</b>Dokumentacja</span><span><b>04</b>Pełne warunki</span></div><div style={{marginTop:22,padding:18,border:'1px solid #38434a',borderRadius:12,background:'rgba(8,15,19,.72)'}}><strong style={{color:'#f0d778'}}>PEŁNE DOSSIER KAŻDEJ OFERTY</strong><p style={{marginBottom:0,color:'#b7b7b7',lineHeight:1.55}}>Każda publikowana oferta ma zawierać materiał zdjęciowy, krótkie wideo/demo lub materiał producenta, zastosowanie, funkcje, cenę, gwarancję, instrukcję/dokumentację oraz status dostępności.</p></div></aside>
    </section>

    <section className="quick-actions"><Link href="/offers/new"><span>01</span><div><strong>ZAMÓW OFERTĘ</strong><small>Szybka wycena B2B</small></div><b>→</b></Link><Link href="/offers/new?product=Finansowanie%20B2B"><span>02</span><div><strong>FINANSOWANIE</strong><small>Indywidualne rozwiązania dla przedsiębiorstw</small></div><b>→</b></Link><Link href="/about"><span>03</span><div><strong>IMPORT</strong><small>Kompleksowa organizacja</small></div><b>→</b></Link><Link href="/contact"><span>04</span><div><strong>KONTAKT Z DORADCĄ</strong><small>Indywidualne wsparcie</small></div><b>→</b></Link></section>

    <section className="section featured-offers-section"><p className="eyebrow">Oryginalne produkty nubia / REDMAGIC</p><h2>Pełne oferty produktowe: zdjęcia, wideo, zastosowanie, funkcje i dokumentacja</h2><p>Każda karta poniżej prezentuje jednolity standard informacji. Cena, wariant, dostępność, dokumenty i warunki gwarancji są ponownie potwierdzane przed zawarciem konkretnej transakcji.</p><div className="featured-offer-grid">{originalSmartphones.map((offer,index)=><article className="featured-offer-card" key={`${offer.brand}-${offer.model}`}>
      <img src={offer.image} alt={`Materiał produktowy ${offer.brand} ${offer.model} — pozycja ${index+1}`}/>
      <div className="featured-offer-copy"><span>ORYGINALNY PRODUKT {index+1}/{originalSmartphones.length}</span><h3>{offer.brand} {offer.model}</h3>
        <div className="home-offer-media-links"><a href={offer.videoUrl} target="_blank" rel="noreferrer">▶ KRÓTKIE WIDEO / DEMO PRODUCENTA ↗</a><a href={offer.manualUrl} target="_blank" rel="noreferrer">INSTRUKCJA / KARTA PRODUKTU ↗</a></div>
        <div className="home-offer-specs"><p><strong>Marka / model:</strong> {offer.brand} {offer.model}</p><p><strong>Do czego można użyć:</strong> {offer.use}.</p><p><strong>Przeznaczenie:</strong> {offer.purpose}.</p><p><strong>Funkcje:</strong> {offer.functions}.</p><p><strong>Benchmark detaliczny UE:</strong> od ok. €{offer.retailEur}</p><p><strong>Dostępność:</strong> {offer.availability}.</p><p><strong>Gwarancja / RMA:</strong> {offer.warranty}.</p><p><strong>Zdjęcia:</strong> materiał prezentacyjny marki; dokładny kolor, pamięć i wariant potwierdzamy w finalnej ofercie.</p></div>
        <strong className="featured-price">Cena PROFESJA: ok. {offer.profesjaPln.toLocaleString('pl-PL')} zł / szt.</strong><Link href={`/offers/new?product=${encodeURIComponent(`${offer.brand} ${offer.model}`)}`}>POPROŚ O PEŁNĄ OFERTĘ →</Link>
      </div></article>)}</div></section>

    <section className="category-section"><div className="section-title-line"><span>PEŁNY KATALOG PRODUKTÓW I ROZWIĄZAŃ B2B</span></div><div className="category-ribbon">{categories.map(([name,sub,icon])=><Link href="/catalog" className="category-tile" key={name}><div className="category-visual">{icon}</div><strong>{name}</strong><span>{sub}</span></Link>)}</div></section>
    <section className="trust-strip"><div><b>01</b><strong>BEZPIECZNE TRANSAKCJE</strong><span>Sprawdzane warunki i dokumentacja</span></div><div><b>02</b><strong>INDYWIDUALNE WYCENY</strong><span>Warunki dopasowane do konkretnego zamówienia</span></div><div><b>03</b><strong>GWARANCJA</strong><span>Warunki potwierdzane przed zakupem</span></div><div><b>04</b><strong>WSPARCIE B2B</strong><span>Dedykowana obsługa na każdym etapie</span></div><div><b>05</b><strong>GLOBALNY ZASIĘG</strong><span>Sourcing i import międzynarodowy</span></div></section>
    <section id="finansowanie" className="section finance-section"><p className="eyebrow">Finansowanie B2B</p><h2>Finansowanie dobierane do konkretnej transakcji</h2><p>Możliwe formy finansowania, dostępność, koszt i warunki zależą od wartości zamówienia, profilu przedsiębiorstwa oraz decyzji wybranego finansującego. PROFESJA może pomóc w przygotowaniu danych transakcji i organizacji procesu, ale nie gwarantuje decyzji kredytowej ani finansowania.</p><Link href="/offers/new?product=Finansowanie%20B2B"><button>ZAPYTAJ O FINANSOWANIE B2B</button></Link></section>
    <section className="section premium-contact-block"><div><p className="eyebrow">Profesja Premium Limited</p><h2>Zapytaj o rozwiązanie dopasowane do Twojej firmy</h2><p>Produkty markowe, sourcing, import, logistyka i finansowanie w jednym procesie obsługi B2B.</p></div><div className="cta-row"><Link href="/catalog"><button>Przejdź do katalogu</button></Link><Link href="/offers/new"><button className="cta-secondary">Złóż zapytanie B2B</button></Link></div></section>
  </main><Footer/></>;
}
